### ISSUE TITLE
draw_graph fails for embedding layer

### ISSUE THREAD

**Issue by Tianmaru** [mert-kurttutan/torchview#22]
While trying to visualize a model with an embedding layer via `draw_graph(model, input_size=(BATCH_SIZE, TRAIN_LENGTH))`, the following error occured:
`RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)`

**Comment by Tianmaru** [comment]
However, works fine with providing `input_data=torch.randint(1,10,(BATCH_SIZE, TRAIN_LENGTH))`.

**Comment by mert-kurttutan** [comment]
Could you provide code so that I can replicate the exact problem/error you experience?
My first guess is that one should explicitly tell the type of input tensor when using embedding layer.
In your case, potential solution would be

```
draw_graph(model, input_size=(BATCH_SIZE, TRAIN_LENGTH), dtype= [torch.long])
```
This should cast input tensor type into `torch.long`. This is probably because in torch embedding layers require tensor of long (int64) format.

**Comment by Tianmaru** [comment]
Your suggested solution with adding `dtypes=[torch.long]` works, so I guess this is a valid solution for this issue - I am sorry, I didn't know you could provide the dtype. Thank you, I will close this issue.

Anyway, here is some minimal example:
```
class LSTMNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = nn.Embedding(10, 100)
        self.lstm = nn.LSTM(input_size=100, hidden_size=50)
        self.fc = nn.Linear(50, 1)
    
    def forward(self, x):
        x = self.embedding(x)
        output, (hn, cn) = self.lstm(x)
        x = self.fc(hn)
        x = torch.flatten(x)
        return x

lstm_net = LSTMNet()
model_graph = draw_graph(lstm_net, input_size=(BATCH_SIZE, TRAIN_LENGTH))
model_graph.visual_graph
```

Maybe one last remark: I like the visualization from torchview more than alternatives like torchviz, since it is close to the keras visualization. However, I think it is a bit confusing, that the first node below the input represents the network as a whole. That way, the shapes doesn't add up if you follow the graph edges. For example, I am referring to the LSTMNet-0 Node in this image:
![grafik](https://user-images.githubusercontent.com/27966972/203092615-cd7647f0-157b-4a5c-bd40-400adbef7a09.png)

**Comment by mert-kurttutan** [comment]
Yeah, regarding hierarchy of modules, you are totally right. In fact, this is mentioned already here #19 
This is something I will release the possible solution for soon.
If you are curious, you can read the problem (which you already described) and potential solution in #19 .

**Comment by mert-kurttutan** [comment]
Also, you had the same mindset for this tool that I had. I wanted it to resemble `keras` plot_models, but for pytorch (also some additional features, e.g. rolling recursive networks)

**Comment by mert-kurttutan** [comment]
In the new version, the problem about repetition of modules has been resolved, where a new parameter `expand_nested` is introduced. This basically chooses to show nested modules with dashed lines
