### ISSUE TITLE
How to save the diagram?

### ISSUE THREAD

**Issue by iucario** [mert-kurttutan/torchview#35]
Would you please tell me how to save the diagram to a png or svg file?
Thanks in advance.

**Comment by mert-kurttutan** [comment]
You have 2 options (which do the same thing)

1. Set the `save_graph=True` when calling `draw_graph`
or
2. Use the result graph: 
```
model_graph = draw_graph(...)
model_graph.visual_graph.render(format='png')
```
Note: There is also directory argument in `draw_graph` if you want to change the location to save the image.
