### ISSUE TITLE
landscape parameter

### ISSUE THREAD

**Issue by turian** [mert-kurttutan/torchview#56]
**Is your feature request related to a problem? Please describe.**

Some graphs are very tall. So showing them left-to-right, not top-to-bottom, might be good on most landscape mode displays.

**Describe the solution you'd like**

landscape=False, but when true, the visualization goes left-to-right. (Not rotated, it should be easy to read.)

**Describe alternatives you've considered**

Manipulating the dot with graphviz directly

**Screenshots / Text**

This tensorboard / wandb cell would look much better in landscape mode:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/65918/209359335-808aa761-09c3-464f-9d59-3e88e45dfae4.png">

**Comment by mert-kurttutan** [comment]
I think this can be implemented through `rankdir` argument for `Digraphviz`.
I will make the changes to include this since this situation seems to be frequent enough. 1-2 day after the change, a new version will be probably be released.

**Comment by mert-kurttutan** [comment]
Just merged to the code that introduced feature, with parameters, `graph_dir` with options `'TB', 'LR', 'BT', 'RL'` as specified in doc string of the function `draw_graph`

Example output can be seen in the tests/test_output directory

This is a typical ensemble model:

![simple_ensemble gv](https://user-images.githubusercontent.com/88637659/209460895-863bfed4-c4d6-4193-ae83-890212a57f2f.png)

**Comment by mert-kurttutan** [comment]
New Release is uploaded with this option available.
I am closing this, Don't hesitate to reopen if you see any issue

**Comment by Nyphet** [comment]
I have a model that I'd like to print in landscape, but as you can see the image ends up way too long. I'd like for it to have some "linebreaks" such that, for example, in the first line there are the first 4 nodes, then in the second one the next 4 nodes, and so on.

![DNN gv](https://github.com/mert-kurttutan/torchview/assets/65339023/d2b40119-13c6-43af-9729-dc2b6ea902d0)
