### ISSUE TITLE
save_graph_format

### ISSUE THREAD

**Issue by turian** [mert-kurttutan/torchview#64]
**Is your feature request related to a problem? Please describe.**

I am getting PNGs with graph_dir=LR that are too small to read.

**Describe the solution you'd like**
I'd like save_graph_format so I could output "svg" or "PDF" or other formats that graphviz supports.

**Describe alternatives you've considered**
Forking and hacking the format so it's not always PNG.

**Screenshots / Text**

My graph is 4839 x 325, which is just too small to read.

![image](https://user-images.githubusercontent.com/65918/211127426-df9f05f9-7c3f-4197-a992-932e805e52cd.png)

**Comment by mert-kurttutan** [comment]
Just so I understand correctly, 
Does the following code work for you?
``model_graph.visual_graph.render(format='svg')``

If it does, I don't want to make `draw_graph` API too crowded.

Also, if preferred png (rather than svg) since it sometimes clips the image unexpectedly

**Comment by mert-kurttutan** [comment]
There is the `model_graph.resize_graph` function whose one argument is `scale`. `scale` scales the image size. If you try `scale > 1`, the image should get bigger. You can try different values to see what value is high enough. At the moment, this is far from ideal essential because of  how graphviz sets its image size, which depends many factors, node size, number of nodes etc.

Certainly, one thing that could be done is to use different default values of image size for horizontal setting

**Comment by turian** [comment]
This is great, thank you! Might I suggest this get added to the docs?

**Comment by turian** [comment]
There's apparently a lot more possible than I realized with this library :)

**Comment by mert-kurttutan** [comment]
> This is great, thank you! Might I suggest this get added to the docs?

Sure. Any pr or suggestion for format would be valuable.
I might change the format of docs. Do you think website dedicated to docs would be beneficial or is readme page enough for docs?

**Comment by kadirnar** [comment]
@mert-kurttutan 

## PNG
```
from torchyolo.predict import YoloHub

model = YoloHub(model_type="yolov5", model_path="yolov5n.pt", device="cuda:0", image_size=640)
model.view_model(file_format="png")
```
<img width="200" alt="teaser" src="https://user-images.githubusercontent.com/36204372/212522884-e70eb23e-07b8-495e-95d2-4d9b4e6c519a.png">

## SVG
```
from torchyolo.predict import YoloHub

model = YoloHub(model_type="yolov5", model_path="yolov5n.pt", device="cuda:0", image_size=640)
model.view_model(file_format="svg")
```
<img width="200" alt="teaser" src="https://user-images.githubusercontent.com/36204372/212522891-c61bbaa3-c11b-4f48-8d53-df7923e901cd.svg">

**Comment by turian** [comment]
@mert-kurttutan I think README is fine, and a lot of people just look at what's on pypi.

On the other hand if you have good docstrings documenting the params, then turning that into documentation automatically could be useful.

**Comment by kvnptl** [comment]
```
model_graph.resize_graph(scale=5.0)
model_graph.visual_graph.render(format='svg')
```
Resizing and saving a graph as SVG is working fine for me.
