### ISSUE TITLE
Rendering in Jupyter Lab

### ISSUE THREAD

**Issue by xluxf** [mert-kurttutan/torchview#76]
**Describe the bug**
When drawing a graph in Jupyter Lab in 'SVG' format, the resulting plot does not cover the whole graph. If I change the format to 'PNG' or 'JPG,' then it plots only low-resolution images. The same behavior occurs when I save the graph to a file.

**To Reproduce**

>from torchview import draw_graph
>from torchvision.models import AlexNet
>
>model_graph1 = draw_graph(AlexNet(), input_size=(1,3,224,224), save_graph=True)
>model_graph1.visual_graph

Ubuntu 20.01
Firefox, Chrome
graphviz==0.20
torchvision==0.10.1+cu111
torchview==0.2.5
jupyter lab==3.0.0

![image](https://user-images.githubusercontent.com/22832928/214549550-aeb0c14b-13af-4dea-afeb-6c5031df6b3a.png)

**Additional context**
Needed for a teaching purpose.

**Comment by mert-kurttutan** [comment]
There is a `model_graph.resize_graph(x)` method where `x` scale factor is essentially rescales the size of graph. In your case, it seems that the size of figure has to be bigger to contain the graph, so you can try

```python
x = 2   # > 1
model_graph1.resize_graph(x)
```

Note that `resize_graph` might not be idempotent for some cases.

**Comment by xluxf** [comment]
Thanks, now it works!
