### ISSUE TITLE
not able to pip install

### ISSUE THREAD

**Issue by athus1990** [mert-kurttutan/torchview#78]
pip is not fining your pckage for python3.6

**Comment by athus1990** [comment]
pip install git+https://github.com/mert-kurttutan/torchview.git seems succesfull but when I do import torchview it is not found

**Comment by mert-kurttutan** [comment]
Could you try to update `setuptools`?
```
pip install setuptools --upgrade
```
Then, it should be fine

**Comment by mert-kurttutan** [comment]
Also, official support is for python version +3.7, (based on python end of life schedule)

**Comment by athus1990** [comment]
I tried pip install -U setuptools updated it. But still pip is not findind your pckage.
I am unable to update to python to 3.7 at the moment due to other dependencies.
 
I get this error on pip install.
ERROR: Could not find a version that satisfies the requirement torchview (from versions: none)
ERROR: No matching distribution found for torchview

**Comment by mert-kurttutan** [comment]
It might be that setuptools version that resolves the issue is not compatible with 3.6.

The installation requires python version >=3.7 (as seen in pypi package, as the package tested on this version)

Another way to go is to install from source code:
```
git clone https://github.com/mert-kurttutan/torchview.git
cd torchview
pip install torchview
```

I cannot promise if it will work since I did not test it on python=3.6

**Comment by athus1990** [comment]
It appears to gove me the same error

` 
pip install git+https://github.com/mert-kurttutan/torchview.git
Collecting git+https://github.com/mert-kurttutan/torchview.git
  Cloning https://github.com/mert-kurttutan/torchview.git to /tmp/pip-req-build-lo_e44_z
  Running command git clone -q https://github.com/mert-kurttutan/torchview.git /tmp/pip-req-build-lo_e44_z
  Resolved https://github.com/mert-kurttutan/torchview.git to commit 00bd35b9bbb6e21df2613fcc89ce3f4833edf767
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
.` 
Seems to not throw an error but doenst seem to install.

**Comment by athus1990** [comment]
I think it works ! thanks!
Afer I did pip install torchview/ 

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (PEP 517) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1795 sha256=a0dbc7f024effd2924775708bc25f7cb3c3f265025ef0318eae691efa2995116
  Stored in directory: /tmp/pip-ephem-wheel-cache-7uujkp3b/wheels/7b/3f/87/79e65aa15874aa7b04c30ee2bdce2f1d31c78ef09fe8aa95da
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
```

**Comment by athus1990** [comment]
Sorry I think something is messed up.
I will try upgrading to 3.7
```
>>> from torchview import draw_graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'draw_graph'
>>> import torchview
>>> from torchview import draw_graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'draw_graph'
```

**Comment by mert-kurttutan** [comment]
Yeah, I think the issue is with regards to pyproject.toml (which I chose since this seems to be the standard for the future (NOT PAST) of python package metadata) and setuptools compatibility. For this, you would need to write setup.cfg equilavent to pyproject.toml of this project, which would require more work than upgrading python, I think :)
