### ISSUE TITLE
how to set two or more input,such as [x1,x2]

### ISSUE THREAD

**Issue by miderxi** [mert-kurttutan/torchview#81]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Screenshots / Text**
When showing piece of code/error, please always prefer text format (over screenshot of the code/error) unless screenshot is absolutely necessary.
If you provide text format (that is executable), it is easier to copy and paste.

**Additional context**

**Comment by miderxi** [comment]
i do not know weather can set input for two or more

**Comment by miderxi** [comment]
you can close this isue,I know it can have two or more input

**Comment by mert-kurttutan** [comment]
Yes, multiple input is an available feature. E.g.
```python
def model(input_1, input_2):
    # model forward definition


from torchview import draw_graph

batch_size = 2
# device='meta' -> no memory is consumed for visualization
model_graph = draw_graph(model, input_data=[input1, input2])
model_graph.visual_graph

```
