### ISSUE TITLE
View model.ckpt

### ISSUE THREAD

**Issue by andreadaou** [mert-kurttutan/torchview#86]
Hello @mert-kurttutan ,

I appreciate your amazing and extremely helpful work.

How can I visualize a **model.ckpt** saved file as in [Notebook Example](https://colab.research.google.com/github/mert-kurttutan/torchview/blob/main/docs/docs/tutorial/notebook/example_vision.ipynb) ? I only have the **.ckpt** file format.

Thank you in advance !

**Comment by mert-kurttutan** [comment]
Torchview api works only of models in memory. 
So, loading the memory first and then using loaded model for `draw_graph` should work.
For details on loading the model, please see https://pytorch.org/tutorials/beginner/saving_loading_models.html
